#!/usr/bin/env bash

# check for argument
if [ $# -eq 0 ]; then
	echo "Usage: $0"
	exit 1
fi

# extract IP from argument
ip_address=$1

# ping IP 5 times
ping -c 5 $ip_address

# check exit status of ping cmd
if [ $? -eq 0 ]; then
	echo "ping completed successfuly."
else
	echo "ping failed."
fi
