#!/usr/bin/env bash
# check for argument
if [ $# -eq 0 ]; then
	echo "Usage: $0 {IP_ADDRESS}"
	exit 1
fi

# extract IP from argument
IP_ADDRESS=$1

# Ping IP 5 times then exit

if ping -c 5 "$IP_ADDRESS"; then
	echo "Ping completed successfully."
else
	echo "Ping failed."
fi
